spring.datasource.url=${DEV_DATABASE_URL}
spring.datasource.username=${DEV_USERNAME}
spring.datasource.password=${DEV_PASSWORD}

# CROSS ORIGIN til localhost
app.cors.allowed-origins=http://localhost:63342

# viser SQL logs
spring.jpa.show-sql=true
# opdatere lokal db hvis der kommer ændringer i entiteterne uden at slette noget i scheme.
spring.jpa.hibernate.ddl-auto=update

# debugger security filters i dev
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# JWT Token til dev
app.jwt.secret=b0f39987ea9d40b8a47d5e69fa5c4e9cb552cda1f910cd84e9a518e91d9a698c