spring.datasource.url=${DEV_DATABASE_URL}
spring.datasource.username=${DEV_USERNAME}
spring.datasource.password=${DEV_PASSWORD}

# CROSS ORIGIN til localhost
app.cors.allowed-origins=http://localhost:63342

# viser SQL logs
spring.jpa.show-sql=true
# opdatere lokal db hvis der kommer ændringer i entiteterne uden at slette noget i scheme.
spring.jpa.hibernate.ddl-auto=update