spring.application.name=EksamensProjekt-qrecycle
spring.profiles.active=prod

# API KEYS
google.api.key=${GOOGLE_API_KEY}

# holder forbindelser åbne så databasen loader hurtigere
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# disabler dårlig springboot default der holder forbindelser åbne i for lang tid
spring.jpa.open-in-view=false

# timeout på jsession cookie (hvor længe user er logget ind)
server.servlet.session.timeout=5m