spring.datasource.url=${DEV_DATABASE_URL}
spring.datasource.username=${DEV_USERNAME}
spring.datasource.password=${DEV_PASSWORD}

# CROSS ORIGIN til localhost
app.cors.allowed-origins=http://localhost:63342

# viser SQL logs
spring.jpa.show-sql=true
# opdatere lokal db hvis der kommer ændringer i entiteterne uden at slette noget i scheme.
spring.jpa.hibernate.ddl-auto=update

# debugger security filters i dev
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# JWT Token til dev
app.jwt.secret=sighl3ASghio4y6ASg446asFDGA4haRasdgagnl433awsildfgjlisnrweg
app.jwt.expiration=86400000